// Cambridge IGCSE syllabus topics, keyed by syllabus code.
// Used to preload the topic tracker so students rate real syllabus units
// (red / amber / green) instead of typing topics from scratch.
// Subjects without a preset list fall back to custom topics added by the student.

export const IGCSE_TOPICS: Record<string, string[]> = {
  // Mathematics
  "0580": [
    "Number",
    "Fractions, decimals and percentages",
    "Ratio and proportion",
    "Indices and standard form",
    "Algebraic manipulation",
    "Equations and inequalities",
    "Sequences",
    "Graphs of functions",
    "Coordinate geometry",
    "Angles and geometric reasoning",
    "Similarity and congruence",
    "Mensuration (area, volume, surface area)",
    "Trigonometry",
    "Vectors and transformations",
    "Probability",
    "Statistics and data handling",
  ],
  // Additional Mathematics
  "0606": [
    "Functions",
    "Quadratic functions",
    "Equations, inequalities and graphs",
    "Indices and surds",
    "Factors of polynomials",
    "Simultaneous equations",
    "Logarithmic and exponential functions",
    "Straight line graphs",
    "Circular measure",
    "Trigonometry",
    "Permutations and combinations",
    "Series",
    "Vectors in two dimensions",
    "Differentiation",
    "Integration",
    "Kinematics",
  ],
  // Physics
  "0625": [
    "Motion (speed, velocity, acceleration)",
    "Forces and momentum",
    "Work, energy and power",
    "Pressure",
    "Thermal physics (kinetic model, heat transfer)",
    "Waves — general properties",
    "Light (reflection, refraction, lenses)",
    "Sound",
    "Electromagnetic spectrum",
    "Electricity (circuits, current, voltage, resistance)",
    "Electromagnetism and motors",
    "Nuclear physics (radioactivity)",
    "Space physics",
  ],
  // Chemistry
  "0620": [
    "States of matter",
    "Atoms, elements and compounds",
    "Ionic and covalent bonding",
    "Stoichiometry (moles, formulae, equations)",
    "Electrochemistry",
    "Chemical energetics",
    "Rate of reaction",
    "Reversible reactions and equilibrium",
    "Redox reactions",
    "Acids, bases and salts",
    "The Periodic Table",
    "Metals and reactivity series",
    "Chemistry of the environment",
    "Organic chemistry",
    "Experimental techniques and chemical analysis",
  ],
  // Biology
  "0610": [
    "Characteristics and classification of living organisms",
    "Cells and organisation of the organism",
    "Movement into and out of cells (diffusion, osmosis)",
    "Biological molecules",
    "Enzymes",
    "Plant nutrition (photosynthesis)",
    "Human nutrition and digestion",
    "Transport in plants",
    "Transport in animals (heart, circulation)",
    "Diseases and immunity",
    "Gas exchange and respiration",
    "Excretion in humans",
    "Coordination and response (nervous system, hormones)",
    "Reproduction",
    "Inheritance and genetics",
    "Variation and natural selection",
    "Organisms and their environment (ecology)",
    "Human influences on ecosystems",
    "Biotechnology and genetic modification",
  ],
  // Combined Science (uses condensed versions of the three sciences)
  "0653": [
    "Cells and organisation (Biology)",
    "Enzymes, nutrition and digestion (Biology)",
    "Respiration and gas exchange (Biology)",
    "Reproduction and inheritance (Biology)",
    "Ecology and the environment (Biology)",
    "Atoms, elements and compounds (Chemistry)",
    "Stoichiometry and chemical reactions (Chemistry)",
    "Acids, bases and the Periodic Table (Chemistry)",
    "Metals and reactivity (Chemistry)",
    "Organic chemistry basics (Chemistry)",
    "Motion, forces and energy (Physics)",
    "Thermal physics and waves (Physics)",
    "Electricity and magnetism (Physics)",
    "Nuclear physics (Physics)",
  ],
  // Co-ordinated Sciences — same structure as combined
  "0654": [
    "Cells and organisation (Biology)",
    "Enzymes, nutrition and digestion (Biology)",
    "Respiration and gas exchange (Biology)",
    "Reproduction and inheritance (Biology)",
    "Ecology and the environment (Biology)",
    "Atoms, elements and compounds (Chemistry)",
    "Stoichiometry and chemical reactions (Chemistry)",
    "Acids, bases and the Periodic Table (Chemistry)",
    "Metals and reactivity (Chemistry)",
    "Organic chemistry basics (Chemistry)",
    "Motion, forces and energy (Physics)",
    "Thermal physics and waves (Physics)",
    "Electricity and magnetism (Physics)",
    "Nuclear physics (Physics)",
  ],
  // Computer Science
  "0478": [
    "Data representation (binary, hex, text, images, sound)",
    "Data transmission and error checking",
    "Hardware (CPU, memory, storage, input/output)",
    "Software and operating systems",
    "The internet and its uses",
    "Automated and emerging technologies",
    "Algorithm design and problem solving",
    "Pseudocode and flowcharts",
    "Programming concepts",
    "Arrays and file handling",
    "Databases and SQL",
    "Boolean logic and logic gates",
  ],
  // ICT
  "0417": [
    "Types and components of computer systems",
    "Input and output devices",
    "Storage devices and media",
    "Networks and their effects",
    "The effects of using IT",
    "ICT applications",
    "The systems life cycle",
    "Safety and security",
    "Audience and communication",
    "Document production",
    "Databases",
    "Presentations",
    "Spreadsheets",
    "Website authoring",
  ],
  // Economics
  "0455": [
    "The basic economic problem",
    "Demand and supply",
    "Price elasticity",
    "Market economic systems and market failure",
    "Money and banking",
    "Households (income, spending, saving)",
    "Workers, trade unions and firms",
    "Government macroeconomic aims",
    "Fiscal, monetary and supply-side policy",
    "Inflation and deflation",
    "Employment and unemployment",
    "Economic growth and living standards",
    "Poverty and population",
    "International trade and globalisation",
    "Exchange rates and balance of payments",
  ],
  // Business Studies
  "0450": [
    "Business activity and classification",
    "Enterprise, business growth and size",
    "Types of business organisation",
    "Business objectives and stakeholders",
    "Motivating employees",
    "Organisation and management",
    "Recruitment, selection and training",
    "Communication in business",
    "Marketing (market research, mix, strategy)",
    "Operations management and production",
    "Costs, scale of production and break-even",
    "Achieving quality and location decisions",
    "Business finance (sources, cash flow, accounts)",
    "External influences (government, environment, ethics)",
  ],
  // Accounting
  "0452": [
    "The double entry system",
    "Books of prime entry",
    "Ledger accounts and trial balance",
    "Bank reconciliation",
    "Correction of errors",
    "Depreciation and disposals",
    "Accruals and prepayments",
    "Bad debts and provisions",
    "Financial statements — sole traders",
    "Financial statements — partnerships",
    "Financial statements — limited companies",
    "Clubs and societies / incomplete records",
    "Accounting ratios and interpretation",
  ],
  // English First Language
  "0500": [
    "Reading comprehension (explicit and implicit meaning)",
    "Summary writing",
    "Analysing writers' effects (language analysis)",
    "Directed writing (letters, speeches, articles)",
    "Extended response to reading",
    "Descriptive writing",
    "Narrative writing",
    "Grammar, spelling and punctuation accuracy",
  ],
  // English Second Language
  "0510": [
    "Reading — skimming, scanning and detail",
    "Note-making",
    "Summary writing",
    "Informal writing (emails, letters)",
    "Formal writing (reports, articles, essays)",
    "Listening comprehension",
    "Speaking (conversation and topic discussion)",
    "Vocabulary and grammar accuracy",
  ],
  // English Literature
  "0475": [
    "Poetry analysis",
    "Prose analysis (set novel/short stories)",
    "Drama analysis (set play)",
    "Unseen texts",
    "Themes and character development",
    "Writer's methods (language, structure, form)",
    "Contextual understanding",
    "Essay writing technique",
  ],
  // Geography
  "0460": [
    "Population dynamics",
    "Migration",
    "Population structure and settlement",
    "Urbanisation and urban problems",
    "Earthquakes and volcanoes",
    "Rivers and river landscapes",
    "Coasts and coastal landscapes",
    "Weather and climate",
    "Ecosystems (tropical rainforest, desert)",
    "Development and inequality",
    "Food production and industry",
    "Tourism",
    "Energy and water resources",
    "Environmental risks and management",
    "Geographical skills (maps, fieldwork)",
  ],
  // History (20th century core)
  "0470": [
    "The First World War and the peace treaties 1919–23",
    "The League of Nations in the 1920s–30s",
    "The collapse of international order in the 1930s",
    "Origins of the Cold War 1945–49",
    "Containment: Korea, Vietnam, Cuba",
    "Soviet control of Eastern Europe",
    "Events in the Gulf 1970–2000",
    "Depth study (e.g. Germany 1918–45)",
    "Source analysis skills",
    "Essay and structured answer technique",
  ],
};

/** Preset topic list for a syllabus code, or empty array if we don't have one. */
export function topicsForCode(code: string | null | undefined): string[] {
  if (!code) return [];
  return IGCSE_TOPICS[code.trim()] ?? [];
}
